name: Release

on:
  create:
    branches:
    - 'master'
    tags:
    - v*

jobs:
  release:
    name: Release on GitHub
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Tests
      run: |
        go mod tidy
        go test -v ./...

    - name: Validates GO releaser config
      uses: goreleaser/goreleaser-action@v2
      with:
        args: check

    - name: Login to DockerHub
      uses: docker/login-action@v1
      if: success() && env.LATEST != ''
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Create release on GitHub
      uses: goreleaser/goreleaser-action@v2
      if: success() && startsWith(github.ref, 'refs/tags/')
      with:
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
